function [x_ddot,y_ddot,psi_ddot] = BiSteer2D_PoseDoubleDerivatives(Ip,Tf,Tr,Vr,Vr_dot,delF,delR,delF_dot,delR_dot,lF,lR,m,psi)
%BiSteer2D_PoseDoubleDerivatives
%    [X_DDOT,Y_DDOT,PSI_DDOT] = BiSteer2D_PoseDoubleDerivatives(Ip,Tf,Tr,Vr,Vr_dot,delF,delR,delF_dot,delR_dot,lF,lR,M,PSI)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    06-Jun-2023 23:08:46

t2 = cos(delF);
t3 = cos(delR);
t4 = sin(delF);
t5 = sin(delR);
t6 = delR+psi;
t7 = lF+lR;
t8 = Vr.^2;
t9 = delF.*2.0;
t10 = delR.*2.0;
t11 = lF.^2;
t12 = lR.^2;
t19 = lF.*lR.*m;
t21 = -delR;
t13 = cos(t9);
t14 = cos(t10);
t15 = t2.^2;
t16 = t2.^3;
t17 = t3.^2;
t18 = cos(t6);
t20 = sin(t6);
t22 = -t10;
t23 = 1.0./t2;
t24 = m.*t11;
t25 = m.*t12;
t26 = delF+t21;
t27 = 1.0./t7;
t31 = t9+t21;
t41 = Ip.*Vr.*delF_dot.*t2.*t3.*t5;
t42 = Ip.*Vr.*delR_dot.*t2.*t3.*t5;
t50 = Vr.*delF_dot.*t2.*t3.*t5.*t19;
t28 = sin(t26);
t29 = t13.*t19;
t30 = t14.*t19;
t32 = t9+t22;
t34 = Tr.*t11.*t16;
t35 = Tr.*t12.*t16;
t36 = Tr.*lF.*lR.*t16.*2.0;
t37 = t13.*t24;
t38 = t14.*t25;
t39 = Ip.*Vr.*delF_dot.*t4.*t17;
t40 = Ip.*Vr.*delR_dot.*t4.*t15;
t43 = Tf.*t3.*t11.*t15;
t44 = Tf.*t3.*t12.*t15;
t45 = Tf.*lF.*lR.*t3.*t15.*2.0;
t47 = Vr.*delR_dot.*t4.*t15.*t19;
t51 = Ip.*Vr.*delR_dot.*t3.*t5.*t16.*2.0;
t52 = Vr.*delF_dot.*t4.*t17.*t25;
t53 = Vr.*delR_dot.*t2.*t3.*t5.*t25;
t57 = -t50;
t58 = Vr.*delR_dot.*t3.*t5.*t16.*t19.*2.0;
t33 = cos(t32);
t48 = -t39;
t49 = -t40;
t56 = -t51;
t59 = -t52;
t60 = t17.*t40.*2.0;
t61 = t17.*t47.*2.0;
t46 = Ip.*t33;
t54 = t19.*t33;
t62 = -t61;
t55 = -t46;
t65 = t34+t35+t36+t41+t42+t43+t44+t45+t47+t48+t49+t53+t56+t57+t58+t59+t60+t62;
t63 = Ip+t19+t24+t25+t29+t30+t37+t38+t54+t55;
t64 = 1.0./t63;
x_ddot = -Vr.*delR_dot.*t20+t18.*t23.*t64.*t65.*2.0-t8.*t20.*t23.*t27.*t28;
if nargout > 1
    y_ddot = Vr.*delR_dot.*t18+t20.*t23.*t64.*t65.*2.0+t8.*t18.*t23.*t27.*t28;
end
if nargout > 2
    psi_ddot = (t27.*(Vr_dot.*t5-Vr_dot.*sin(t31)-Vr.*delF_dot.*t3.*2.0+Vr.*delR_dot.*t3+Vr.*delR_dot.*cos(t31)).*(-1.0./2.0))./t15;
end
end
