function phiddot = TiltAngularAcceleration(Ac,Ip,Iw,M,g,l,m,phi,r)
%TiltAngularAcceleration
%    PHIDDOT = TiltAngularAcceleration(Ac,Ip,Iw,M,G,L,m,PHI,R)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    05-Jun-2023 02:31:06

t2 = cos(phi);
phiddot = -(Ac.*Iw+Ac.*M.*r.^2+Ac.*M.*l.*r.*t2+Ac.*l.*m.*r.*t2-M.*g.*l.*r.*sin(phi))./(Ip.*r+l.^2.*m.*r);
end
